### ISSUE TITLE
How to merge this project with Symfony 4 & Doctrine?

### ISSUE THREAD

**Issue by zesanriky** [Piyushhbhutoria/OnlineClinicSystem#12]
I find your project is pretty interesting. I want to use this project for further development. But the condition is that I must use the Symfony framework and  Doctrine with
MySQL as the main entities which will be driving my solution.

Any suggestions would be appreciated.

**Comment by Piyushhbhutoria** [comment]
shifting this code on to a framework, I am not sure how much work it will take, I don't have experience with PHP frameworks.
If you think there's a lot of work migrating you can start from scratch using the template - WPF medinova. It's an HTML, CSS, bootstrap template. 
I can surely help you if you get stuck somewhere.
